name: Build And Deploy

on:
    push:
        branches: main
        paths-ignore:
            - "*.md"
    workflow_dispatch:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: "npm"

            - name: Install Dependencies
              run: npm install

            - name: Build project
              run: npm run build

            - name: deploy to gh-pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: "./dist"
